name: 🐛 Bug Report
description: Create a report to help us improve
title: "[🐛 Bug Report]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Steps to reproduce the behavior
      placeholder: Tell us how to reproduce the behavior
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: Provide information about your environment (i.e., Python version, OS).
  - type: textarea
    id: additional-content
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here.
